# Right now tests don't work on CircleCI. I'm not sure why, but other people
# have the same issue: https://github.com/CircleCI-Public/go-orb/issues/69. 
#
# If the above gets fixed, try adding this project to CircleCI again.

version: '2.1'
orbs:
  go: circleci/go@1
jobs:
  build:
    executor:
      name: go/default
      tag: '1.20.1'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
  main:
    jobs:
      - build
